# -*- coding: utf-8 -*-
"""bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIvc9Fbn3Vi6QAx3xjJiEUyw04sDlL-w
"""

import ccxt
import pandas as pd
import ta
import requests
import time
import os
from dotenv import load_dotenv

# 🔐 Laad .env
load_dotenv()
TOKEN = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

exchange = ccxt.kraken()
last_signals = {}
last_update_time = {}
SYMBOLS = ["BTC/USD", "ETH/USD", "SOL/USD"]
RISK_PER_TRADE = 0.01  # 1% risk per trade
UPDATE_INTERVAL = 14400  # 4 uur
INITIAL_BALANCE = 1000

# Init last_signals & last_update_time
for s in SYMBOLS:
    last_signals[s] = None
    last_update_time[s] = 0

# Telegram functie
def send_message(text):
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    try:
        requests.post(url, data={"chat_id": CHAT_ID, "text": text}, timeout=10)
        print("Bericht gestuurd!")
    except Exception as e:
        print("Telegram fout:", e)

# Data ophalen
def get_data(symbol, timeframe="15m", limit=500):
    ohlc = exchange.fetch_ohlcv(symbol, timeframe=timeframe, limit=limit)
    df = pd.DataFrame(ohlc, columns=['t','o','h','l','c','v'])
    df['ema9'] = ta.trend.EMAIndicator(df['c'], window=9).ema_indicator()
    df['ema21'] = ta.trend.EMAIndicator(df['c'], window=21).ema_indicator()
    df['ema50'] = ta.trend.EMAIndicator(df['c'], window=50).ema_indicator()
    df['ema200'] = ta.trend.EMAIndicator(df['c'], window=200).ema_indicator()
    df['vol_avg'] = df['v'].rolling(20).mean()
    return df

# Backtest/Live logic per coin
def run_bot():
    balance = {s: INITIAL_BALANCE for s in SYMBOLS}
    position = {s: None for s in SYMBOLS}

    for symbol in SYMBOLS:
        try:
            ticker = exchange.fetch_ticker(symbol)
            price = ticker['last']

            df = get_data(symbol)

            # Trend op 1H
            df_1h = get_data(symbol, timeframe="1h")
            ema50_1h = df_1h['ema50'].iloc[-1]
            ema200_1h = df_1h['ema200'].iloc[-1]
            uptrend = ema50_1h > ema200_1h
            downtrend = ema50_1h < ema200_1h

            # Pullback / breakout
            recent_high = df['h'].iloc[-20:].max()
            recent_low = df['l'].iloc[-20:].min()
            ema9 = df['ema9'].iloc[-1]
            ema21 = df['ema21'].iloc[-1]
            current_vol = df['v'].iloc[-1]
            avg_vol = df['vol_avg'].iloc[-1]

            signal = None

            # ===== ENTRY LOGIC =====
            if uptrend:
                if price > recent_high or price < ema9:
                    signal = "BUY"
            elif downtrend:
                if price < recent_low or price > ema9:
                    signal = "SELL"

            # ===== OPEN POSITION =====
            if position[symbol] is None and signal:
                risk_amount = balance[symbol] * RISK_PER_TRADE
                if signal == "BUY":
                    entry = price
                    sl = entry * 0.985
                    tp = entry * 1.03
                else:
                    entry = price
                    sl = entry * 1.015
                    tp = entry * 0.97

                stop_distance = abs(entry - sl)
                if stop_distance == 0:
                    continue
                position_size = risk_amount / stop_distance

                position[symbol] = {"type": signal, "entry": entry, "sl": sl, "tp": tp, "size": position_size}

            # ===== MANAGE POSITION =====
            elif position[symbol]:
                high = df['h'].iloc[-1]
                low = df['l'].iloc[-1]

                hit_tp = hit_sl = False
                if position[symbol]["type"] == "BUY":
                    if low <= position[symbol]["sl"]:
                        hit_sl = True
                    elif high >= position[symbol]["tp"]:
                        hit_tp = True
                else:
                    if high >= position[symbol]["sl"]:
                        hit_sl = True
                    elif low <= position[symbol]["tp"]:
                        hit_tp = True

                if hit_tp or hit_sl:
                    if hit_tp:
                        profit = balance[symbol] * 0.02  # RR 2%
                    else:
                        profit = -balance[symbol] * RISK_PER_TRADE
                    balance[symbol] += profit
                    position[symbol] = None
                    send_message(f"💰 {symbol} {signal} gesloten. Profit: {round(profit,2)} | Balance: {round(balance[symbol],2)}")

            # ===== TELEGRAM UPDATES =====
            current_time = time.time()
            time_passed = current_time - last_update_time[symbol]

            if (signal != last_signals[symbol]) or (time_passed >= UPDATE_INTERVAL):
                trend_emoji = "📈" if uptrend else "📉" if downtrend else "↔️"
                vol_emoji = "✅" if current_vol > avg_vol else "❌"
                header = "🚨 Nieuw signaal" if signal != last_signals[symbol] else "🔄 Update (geen verandering)"
                message = (
                    f"{header}\n"
                    f"🔔 {symbol}\n"
                    f"Prijs: {price}\n"
                    f"Trend: {trend_emoji}\n"
                    f"Volume: {vol_emoji}\n"
                    f"Advies: {signal}"
                )
                send_message(message)
                last_signals[symbol] = signal
                last_update_time[symbol] = current_time

            print(f"{symbol}: {price} | Trend: {'UP' if uptrend else 'DOWN'} | Signaal: {signal}")

        except Exception as e:
            print(f"Fout bij {symbol}: {e}")
            continue
        time.sleep(1)


# 🔹 Start loop
while True:
    run_bot()
    print("Scan voltooid. Wacht 15 minuten...")
    time.sleep(900)  # update elke 15 min