# -*- coding: utf-8 -*-
"""bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIvc9Fbn3Vi6QAx3xjJiEUyw04sDlL-w
"""

import ccxt
import pandas as pd
import ta
import requests
import time
import os
from dotenv import load_dotenv

# =========================
# 🔐 ENV
# =========================
load_dotenv()
TOKEN = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

# =========================
# 🔌 EXCHANGE
# =========================
exchange = ccxt.kraken()

SYMBOLS = ["BTC/USD", "ETH/USD", "SOL/USD"]

UPDATE_INTERVAL = 14400  # 4 uur

last_signals = {s: None for s in SYMBOLS}
last_update_time = {s: 0 for s in SYMBOLS}

# =========================
# 📩 TELEGRAM
# =========================
def send_message(text):
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    try:
        requests.post(url, data={
            "chat_id": CHAT_ID,
            "text": text
        }, timeout=10)
        print("📩 Bericht gestuurd!")
    except Exception as e:
        print("Telegram fout:", e)

# =========================
# 📊 DATA
# =========================
def get_data(symbol, timeframe="1h", limit=200):
    ohlc = exchange.fetch_ohlcv(symbol, timeframe=timeframe, limit=limit)

    df = pd.DataFrame(ohlc, columns=['t','o','h','l','c','v'])

    df['rsi'] = ta.momentum.rsi(df['c'], window=14)
    df['vol_avg'] = df['v'].rolling(20).mean()

    return df

# =========================
# 🧠 STRATEGIE
# =========================
def generate_signal(df):
    if len(df) < 50:
        return None

    last = df.iloc[-1]

    structure_df = df.iloc[-50:]

    highs = structure_df['h']
    lows = structure_df['l']

    recent_high = highs.max()
    recent_low = lows.min()

    price = last['c']

    # 🔹 MSB (soepel)
    tolerance = 0.002

    if price > recent_high * (1 - tolerance):
        msb = "BULLISH"
    elif price < recent_low * (1 + tolerance):
        msb = "BEARISH"
    else:
        msb = "NONE"

    # 🔹 RSI
    rsi = last['rsi']
    bullish_rsi = rsi > 50
    bearish_rsi = rsi < 50

    # 🔹 Volume
    volume = last['v']
    avg_volume = last['vol_avg']

    if pd.isna(avg_volume):
        volume_ok = True
    else:
        volume_ok = volume > avg_volume * 0.8

    # 🔹 Levels
    support = recent_low
    resistance = recent_high

    # 🔹 Signal
    signal = "HOLD"

    if msb == "BULLISH" and bullish_rsi and volume_ok:
        signal = "BUY"
    elif msb == "BEARISH" and bearish_rsi and volume_ok:
        signal = "SELL"

    # 🔹 Targets
    if signal == "BUY":
        target = resistance
        stop_loss = support
    elif signal == "SELL":
        target = support
        stop_loss = resistance
    else:
        target = None
        stop_loss = None

    return (
        signal,
        msb,
        support,
        resistance,
        volume_ok,
        rsi,
        target,
        stop_loss
    )

# =========================
# 🤖 BOT LOOP
# =========================
def run_bot():
    for symbol in SYMBOLS:
        try:
            ticker = exchange.fetch_ticker(symbol)
            price = ticker['last']

            df = get_data(symbol)
            result = generate_signal(df)

            if result is None:
                continue

            signal, msb, support, resistance, volume_ok, rsi, target, stop_loss = result

            current_time = time.time()
            time_passed = current_time - last_update_time[symbol]

            # 🚨 NIEUW SIGNAAL
            if signal != last_signals[symbol] and signal != "HOLD":

                message = (
                    f"🚨 NIEUW SIGNAAL\n"
                    f"🔔 {symbol}\n"
                    f"Prijs: {price}\n"
                    f"MSB: {msb}\n"
                    f"RSI: {round(rsi,2)}\n"
                    f"Volume: {'✅' if volume_ok else '❌'}\n"
                    f"Support: {round(support,2)}\n"
                    f"Resistance: {round(resistance,2)}\n"
                    f"🎯 Target: {round(target,2) if target else '—'}\n"
                    f"🛑 Stop Loss: {round(stop_loss,2) if stop_loss else '—'}\n"
                    f"Signaal: {signal}"
                )

                send_message(message)

                last_signals[symbol] = signal
                last_update_time[symbol] = current_time

            # 🤖 HEARTBEAT
            elif time_passed >= UPDATE_INTERVAL:

                message = (
                    f"🤖 BOT STATUS UPDATE (4H)\n"
                    f"🔔 {symbol}\n"
                    f"Prijs: {price}\n"
                    f"MSB: {msb}\n"
                    f"RSI: {round(rsi,2)}\n"
                    f"Volume: {'✅' if volume_ok else '❌'}\n"
                    f"Support: {round(support,2)}\n"
                    f"Resistance: {round(resistance,2)}\n"
                    f"Status: Bot draait correct ✅\n"
                    f"Laatste signaal: {last_signals[symbol]}"
                )

                send_message(message)
                last_update_time[symbol] = current_time

            print(f"{symbol} | {price} | MSB: {msb} | RSI: {round(rsi,2)} | VolOK: {volume_ok} | Signal: {signal}")

        except Exception as e:
            print(f"❌ Fout bij {symbol}: {e}")

        time.sleep(1)

# =========================
# 🔁 MAIN LOOP (ELK UUR)
# =========================
while True:
    run_bot()
    print("🔄 Scan voltooid. Wacht 1 uur...")
    time.sleep(3600)