# -*- coding: utf-8 -*-
"""bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIvc9Fbn3Vi6QAx3xjJiEUyw04sDlL-w
"""

import ccxt
import pandas as pd
import ta
import requests
import time
import os
from dotenv import load_dotenv

# 🔐 Laad .env
load_dotenv()

TOKEN = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

exchange = ccxt.kraken()
last_signal = None


def send_message(text):
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"

    try:
        requests.post(url, data={
            "chat_id": CHAT_ID,
            "text": text
        })
        print("Bericht gestuurd!")
    except Exception as e:
        print("Telegram fout:", e)


# 🔹 Instellingen
SYMBOLS = ["BTC/USD", "ETH/USD", "SOL/USD"]
last_signals = {symbol: None for symbol in SYMBOLS}

def get_support_resistance(df):
    highs = []
    lows = []
    # We kijken naar de laatste 50 kaarsen van 1 uur
    df_recent = df.tail(50)
    for i in range(2, len(df_recent)-2):
        if df_recent['h'].iloc[i] > df_recent['h'].iloc[i-1] and df_recent['h'].iloc[i] > df_recent['h'].iloc[i+1]:
            highs.append(df_recent['h'].iloc[i])
        if df_recent['l'].iloc[i] < df_recent['l'].iloc[i-1] and df_recent['l'].iloc[i] < df_recent['l'].iloc[i+1]:
            lows.append(df_recent['l'].iloc[i])

    resistance = max(highs[-5:]) if highs else df_recent['h'].max()
    support = min(lows[-5:]) if lows else df_recent['l'].min()
    return support, resistance

def get_data(symbol, timeframe="1h"):
    ohlc = exchange.fetch_ohlcv(symbol, timeframe=timeframe, limit=100)
    df = pd.DataFrame(ohlc, columns=['t','o','h','l','c','v'])
    df['rsi'] = ta.momentum.RSIIndicator(df['c']).rsi()
    df['ema9'] = ta.trend.EMAIndicator(df['c'], window=9).ema_indicator()
    df['ema21'] = ta.trend.EMAIndicator(df['c'], window=21).ema_indicator()
    df['vol_avg'] = df['v'].rolling(window=20).mean()
    return df

def run_bot():
    for symbol in SYMBOLS:
        try:
            ticker = exchange.fetch_ticker(symbol)
            price = ticker["last"]

            # Alles op 1-uurs basis
            df_1h = get_data(symbol, "1h")

            rsi_1h = df_1h['rsi'].iloc[-1]
            current_vol = df_1h['v'].iloc[-1]
            avg_vol = df_1h['vol_avg'].iloc[-1]
            high_volume = current_vol > avg_vol

            # Trend bepaling op 1h (EMA Cross)
            ema9_1h = df_1h['ema9'].iloc[-1]
            ema21_1h = df_1h['ema21'].iloc[-1]
            uptrend_1h = ema9_1h > ema21_1h
            downtrend_1h = ema9_1h < ema21_1h

            # Support/Resistance op 1h
            support, resistance = get_support_resistance(df_1h)

            signal = "HOLD"

            # 🟢 BUY LOGICA
            if uptrend_1h and high_volume:
                # Signaal als RSI laag is OF prijs in support zone (1.5%) komt
                if rsi_1h < 45 or price <= (support * 1.015):
                    signal = "BUY"

            # 🔴 SELL LOGICA
            elif downtrend_1h and high_volume:
                # Signaal als RSI hoog is OF prijs in resistance zone komt
                if rsi_1h > 65 or price >= (resistance * 0.985):
                    signal = "SELL"

            # Alleen bericht sturen als het signaal verandert
            if signal != last_signals[symbol]:
                vol_emoji = "✅" if high_volume else "❌"
                trend_emoji = "📈" if uptrend_1h else "📉" if downtrend_1h else "↔️"

                message = (
                    f"🔔 {symbol} (1H)\n"
                    f"Prijs: {price}\n"
                    f"Trend: {trend_emoji}\n"
                    f"RSI: {round(rsi_1h, 2)}\n"
                    f"Volume: {vol_emoji}\n"
                    f"Advies: {signal}"
                )
                send_message(message)
                last_signals[symbol] = signal

            print(f"{symbol}: {price} | RSI: {round(rsi_1h,1)} | Signaal: {signal}")
            time.sleep(1)

        except Exception as e:
            print(f"Fout bij {symbol}: {e}")

# 🔹 Start de loop
while True:
    run_bot()
    print("Scan voltooid. Wacht 1 uur...")
    time.sleep(3600)