# -*- coding: utf-8 -*-
"""pokemon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYv-8bIdm-QbF2db3LDjRbA2-TbFLvBv
"""

import requests
from bs4 import BeautifulSoup
import time
import os
import json
from dotenv import load_dotenv

# =========================
# 🔐 ENV
# =========================
load_dotenv()
TOKEN = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

# =========================
# ⚙️ CONFIG
# =========================
SEARCH_URL = "https://www.bol.com/nl/nl/s/?searchtext=pokemon+kaarten"

CHECK_INTERVAL = 90  # 1.5 minuut
HEARTBEAT_INTERVAL = 86400  # 🔥 24 uur

SEEN_FILE = "seen_products.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0",
    "Accept-Language": "nl-NL,nl;q=0.9"
}

KEYWORDS = [
    "booster",
    "elite trainer",
    "etb",
    "ultra premium",
    "collection",
    "tin",
    "box"
]

# =========================
# ⏱️ TIMERS
# =========================
START_TIME = time.time()
LAST_HEARTBEAT = time.time()

# =========================
# 💾 STORAGE
# =========================
def load_seen():
    if os.path.exists(SEEN_FILE):
        with open(SEEN_FILE, "r") as f:
            return set(json.load(f))
    return set()

def save_seen(seen):
    with open(SEEN_FILE, "w") as f:
        json.dump(list(seen), f)

seen_products = load_seen()

# =========================
# 📩 TELEGRAM
# =========================
def send_message(text):
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    try:
        requests.post(url, data={
            "chat_id": CHAT_ID,
            "text": text
        }, timeout=10)
        print("📩 Bericht gestuurd!")
    except Exception as e:
        print("Telegram fout:", e)

# =========================
# ⏱️ UPTIME
# =========================
def get_uptime():
    seconds = int(time.time() - START_TIME)
    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    return f"{hours}u {minutes}m"

# =========================
# 🔍 FILTER
# =========================
def is_interesting(title):
    title_lower = title.lower()
    return any(k in title_lower for k in KEYWORDS)

# =========================
# 🔎 SCAN
# =========================
def scan_bol():
    global seen_products

    try:
        response = requests.get(SEARCH_URL, headers=HEADERS, timeout=15)
        soup = BeautifulSoup(response.text, "html.parser")

        products = soup.select("li.product-item--row")

        print(f"🔎 {len(products)} producten gescand")

        for product in products:

            title_tag = product.select_one("a.product-title")
            seller_tag = product.select_one(".product-seller__name")
            link_tag = product.select_one("a.product-title")

            if not title_tag or not seller_tag:
                continue

            title = title_tag.text.strip()
            seller = seller_tag.text.strip()
            link = "https://www.bol.com" + link_tag.get("href")

            if "bol" not in seller.lower():
                continue

            if not is_interesting(title):
                continue

            if link in seen_products:
                continue

            seen_products.add(link)
            save_seen(seen_products)

            message = (
                f"🔥 POKEMON RESTOCK!\n\n"
                f"🛒 {title}\n"
                f"🏪 Verkoper: {seller}\n"
                f"⚡ SNIPER HIT\n\n"
                f"🔗 {link}"
            )

            send_message(message)
            print(f"✅ SNIPED: {title}")

    except Exception as e:
        print("❌ Scan fout:", e)

# =========================
# 🔁 LOOP
# =========================
while True:
    print("🔄 Sniper scan...")
    scan_bol()

    # =========================
    # 🤖 24H HEARTBEAT
    # =========================
    current_time = time.time()

    if current_time - LAST_HEARTBEAT >= HEARTBEAT_INTERVAL:
        uptime = get_uptime()

        message = (
            f"🤖 BOT STATUS (24H)\n\n"
            f"✅ Bot draait correct\n"
            f"⏱️ Uptime: {uptime}\n"
            f"📦 Gescande niche: Pokémon kaarten\n"
            f"⚡ Status: Actief"
        )

        send_message(message)

        LAST_HEARTBEAT = current_time

    print(f"⏳ Wacht {CHECK_INTERVAL} sec...\n")
    time.sleep(CHECK_INTERVAL)